name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/lobis/test-env
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: |
          entry-point.sh
          printenv
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          entry-point.sh
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: |
          entry-point.sh
          cd ${{github.workspace}}/build
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure
