name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash -leo pipefail {0} # Removed " --noprofile --norc " options from default bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfieldpp:cxx17_ROOTv6-25-01_Geant4v10.7.3
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN_READ}}

    steps:
      - uses: actions/checkout@v2

      - name: Load .bashrc
        run: source /root/.bashrc

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure
