name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, self-hosted ]
    container:
      image: docker.io/lobis/test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure
