name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lobis/root-geant4-garfieldpp:cxx17_ROOTv6-25-01_Geant4v10.7.3

      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Debug Environment
        run: |
          source entry-point.sh
          root-config --prefix
          root-config --version
          geant4-config --prefix
          geant4-config --version
          echo "GARFIELD: $GARFIELD_INSTALL"

      - name: Configure CMake without testing
        run: |
          source entry-point.sh
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Configure CMake with testing
        run: |
          source entry-point.sh
          rm -rf ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build -DTEST=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          source entry-point.sh
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: |
          source entry-point.sh
          cd ${{github.workspace}}/build
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure
