name: Deploy

on:
  workflow_dispatch:
    inputs:
      targets:
        required: true
        description: name of the target to deploy on. Must be a valid runner.
        default: naf-iaxo

env:
  BUILD_TYPE: Release
  CMAKE_INSTALL_PREFIX: ~/radiation-transport/install

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ github.event.inputs.GEANT4_VERSION }}

    steps:
      - uses: actions/checkout@v2

      - name: Debug Environment
        run: |
          root-config --prefix
          root-config --version
          geant4-config --prefix
          geant4-config --version
          echo "GARFIELD: $GARFIELD_INSTALL"

      - name: Configure CMake without testing
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.CMAKE_INSTALL_PREFIX}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: |
          rm -rf ${{env.CMAKE_INSTALL_PREFIX}}
          cd ${{github.workspace}}/build
          make install
