name: Deploy

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "Build and Test" ]
    branches: [ main ]
    types: [ completed ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ naf-iaxo, sultan, sultan2 ]

    steps:
      - uses: actions/checkout@v2

      - name: Debug Environment
        run: |
          root-config --prefix
          root-config --version
          geant4-config --prefix
          geant4-config --version
          echo "GARFIELD: $GARFIELD_INSTALL"

      - name: Configure CMake without testing
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=~/radiation-transport/install

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: |
          cd ${{github.workspace}}/build
          make install
