name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ naf-iaxo ]

    steps:
      - uses: actions/checkout@v2

      - name: Debug Environment
        run: |
          which root-config
          root-config --version
          which geant4-config
          geant4-config --version
          printenv

      - name: Configure CMake without testing
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=~/software/radiation-transport/install

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: |
          cd ${{github.workspace}}/build
          make install
