name: Create and publish a Docker image

on:
  workflow_dispatch:

env:
  CMAKE_CXX_STANDARD: 17
  ROOT_VERSION: v6-25-01
  GEANT4_VERSION: v10.7.3

  REGISTRY: ghcr.io
  IMAGE_NAME: lobis/root-geant4-garfieldpp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: utils/Docker/ROOT_Geant4_Garfieldpp
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cxx${{ env.CMAKE_CXX_STANDARD }}_ROOT${{ env.ROOT_VERSION }}_Geant4${{ env.GEANT4_VERSION }}
