name: Create and publish a Docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  CMAKE_CXX_STANDARD: 17
  ROOT_VERSION: v6-25-01
  GEANT4_VERSION: v10.7.3
  IMAGE_NAME: lobis/root-geant4-garfieldpp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: utils/Docker/ROOT_Geant4_Garfieldpp
          push: true
          tags: ${{ env.IMAGE_NAME }}:cxx${{ env.CMAKE_CXX_STANDARD }}_ROOT${{ env.ROOT_VERSION }}_Geant4${{ env.GEANT4_VERSION }}
