name: Create and publish base Docker image

on:
  workflow_dispatch:
    inputs:
      CMAKE_CXX_STANDARD:
        description: "CMake C++ Standard"
        required: true
        default: "17"
      ROOT_VERSION:
        description: "ROOT Version"
        required: true
        default: "v6-25-01"
      GEANT4_VERSION:
        description: "Geant4 Version"
        required: true
        default: "v10.7.3"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lobis/root-geant4-garfieldpp

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Build and push base Docker image
        uses: docker/build-push-action@v2
        with:
          context: utils/Docker/ROOT_Geant4_Garfieldpp
          push: true
          build-args: |
            CMAKE_CXX_STANDARD=${{ github.event.inputs.CMAKE_CXX_STANDARD }}
            ROOT_VERSION=${{ github.event.inputs.ROOT_VERSION }}
            GEANT4_VERSION=${{ github.event.inputs.GEANT4_VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cxx${{ github.event.inputs.CMAKE_CXX_STANDARD }}_ROOT${{ github.event.inputs.ROOT_VERSION }}_Geant4${{ github.event.inputs.GEANT4_VERSION }}
