name: Analysis Docker Image

on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        description: name of the target to build image on. 'ubuntu-latest' will always work (but slower) but 'self-hosted' is faster and has cache, but needs to be available
        default: ubuntu-latest
env:
  IMAGE_NAME: lobis/radiation-transport-analysis

jobs:
  build-and-push-image:
    runs-on: ${{ github.event.inputs.target }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: utils/Docker/Analysis/Dockerfile
          push: true
          pull: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:latest